import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from "@next/font/google"

const inter = Inter({ subsets: ['latin'] })

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat"
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>
      <body className={`${montserrat.className} mx-32 my-12`}>
      {children}
      </body>
      
    </html>
  )
}
